Update in-prod-release.yml

diff --git a/.github/workflows/in-prod-release.yml b/.github/workflows/in-prod-release.yml
--- a/.github/workflows/in-prod-release.yml
+++ b/.github/workflows/in-prod-release.yml
@@ -55,14 +55,14 @@ jobs:
           docker push $ECR_REPOSITORY:$IMAGE_TAG
           echo "image=$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
 
-      # - name: update server
-      #   id: update-server
-      #   run: |
-      #     response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/x-www-form-urlencoded" -u "$jenkins_username:$jenkins_pass" -d "service_to_update=$service_name" "$jenkins_url/job/$job_name/buildWithParameters")
-      #     if [ "$response" -eq 201 ]; then
-      #       echo "Success! The response code is $response."
-      #     else
-      #       echo "Failed! The response code is $response."
-      #       exit 1 
-      #     fi
+      - name: update server
+        id: update-server
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/x-www-form-urlencoded" -u "$jenkins_username:$jenkins_pass" -d "service_to_update=$service_name" "$jenkins_url/job/$job_name/buildWithParameters")
+          if [ "$response" -eq 201 ]; then
+            echo "Success! The response code is $response."
+          else
+            echo "Failed! The response code is $response."
+            exit 1 
+          fi
      
